export type SubjectName =
  | 'Matemática'
  | 'Física'
  | 'Química'
  | 'Biologia'
  | 'História'
  | 'Geografia'
  | 'Português'
  | 'Inglês'
  | 'Francês'
  | 'Filosofia'
  | 'Sociologia'
  | 'Economia'
  | 'Direito'
  | 'Psicologia'
  | 'Informática'
  | 'Geometria Descritiva'
  | 'Educação Visual'
  | 'Música'
  | 'Antropologia'
  | 'Literatura';
